In [1]:
import pandas as pd
import numpy as np

In [107]:
df = pd.read_csv("data/premier_league.csv")
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,09/08/2019,20:00,Liverpool,Norwich,4,1,H,4,0,...,3.43,-2.25,1.91,1.99,1.94,1.98,1.99,2.07,1.90,1.99
1,E0,10/08/2019,12:30,West Ham,Man City,0,5,A,0,1,...,2.91,1.75,1.95,1.95,1.96,1.97,2.07,1.98,1.97,1.92
2,E0,10/08/2019,15:00,Bournemouth,Sheffield United,1,1,D,0,0,...,1.92,-0.50,1.95,1.95,1.98,1.95,2.00,1.96,1.96,1.92
3,E0,10/08/2019,15:00,Burnley,Southampton,3,0,H,0,0,...,1.71,0.00,1.87,2.03,1.89,2.03,1.90,2.07,1.86,2.02
4,E0,10/08/2019,15:00,Crystal Palace,Everton,0,0,D,0,0,...,1.71,0.25,1.82,2.08,1.97,1.96,2.03,2.08,1.96,1.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,E0,07/03/2020,15:00,Wolves,Brighton,0,0,D,0,0,...,1.74,-0.75,1.98,1.92,2.01,1.92,2.03,1.99,1.94,1.93
284,E0,07/03/2020,17:30,Burnley,Tottenham,1,1,D,1,0,...,1.74,0.00,1.95,1.95,1.96,1.97,2.00,2.01,1.94,1.92
285,E0,08/03/2020,14:00,Chelsea,Everton,4,0,H,2,0,...,2.13,-0.50,1.85,2.05,1.88,2.04,2.00,2.11,1.86,2.01
286,E0,08/03/2020,16:30,Man United,Man City,2,0,H,1,0,...,1.97,0.75,1.87,2.03,1.85,2.07,1.91,2.11,1.87,2.01
287,E0,09/03/2020,20:00,Leicester,Aston Villa,4,0,H,1,0,...,2.28,-1.00,1.85,2.05,1.88,2.05,1.91,2.08,1.86,2.01

In [108]:
def prediction (odds1,odds2,odds3):
    if odds1<odds3 :
        predict = 0
    elif odds3<odds1 :
        predict = 1
    else:
        predict=2
    return predict

In [109]:
def win_draw_loose(result):
    if result == 'H':
        points = 3
    if result == 'D':
        points = 1
    if result == 'A':
        points =0
    return points

In [110]:
def bookeh_right(result,prediction):
    if result == 3 and prediction == 0:
        is_right = True
    elif result == 0 and prediction == 1:
        is_right = True
    elif result == 1 and prediction ==2:
        is_right = True
    else:
        is_right = False
    return is_right

In [147]:
true = np.array([])
false = np.array([])
list_bookeh = np.array(['B365','BW','IW','PS','VC','WH'])
df['points'] = df['FTR'].apply(win_draw_loose)
for i in range(len(list_bookeh)):
    y = list_bookeh[i]
    df[y+'pred'] = df.apply(lambda x: prediction(x[y+'H'], x[y+'D'],x[y+'A']), axis=1)
    df[y+'right'] = df.apply(lambda x: bookeh_right(x['points'],x[y+'pred']),axis=1)
    true = np.append(true,df[y+'right'].value_counts()[0])
    false = np.append(false,df[y+'right'].value_counts()[1])

In [154]:
d = {'bookeh':list_bookeh,'true': true,'false':false}
prediction_df = pd.DataFrame(data=d)
prediction_df['precision']= prediction_df.true/(prediction_df.true + prediction_df.false)
prediction_df

  bookeh   true  false  precision
0   B365  136.0  152.0   0.472222
1     BW  136.0  152.0   0.472222
2     IW  136.0  152.0   0.472222
3     PS  138.0  150.0   0.479167
4     VC  136.0  152.0   0.472222
5     WH  135.0  153.0   0.468750

In [18]:
df.groupby('HomeTeam').sum().sort_values(by='points',ascending=False)

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,...,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,points
HomeTeam,,,,,,,,,,,,,,,,,,,,,
Liverpool,40,12,23,6,254,144,102,48,116,142,...,-22.50,29.61,28.69,30.14,28.81,30.59,30.38,29.43,28.81,45
Leicester,30,15,9,7,207,142,72,49,154,185,...,-9.25,29.14,29.54,29.52,29.44,30.20,30.38,28.93,29.29,30
Man City,33,12,14,7,279,85,87,34,120,107,...,-28.25,25.81,24.95,26.02,25.04,26.89,26.03,25.69,24.79,29
Man United,29,12,14,6,246,131,94,49,176,175,...,-9.50,29.47,29.35,29.62,29.35,30.08,30.30,29.11,29.14,29
Tottenham,27,15,13,9,187,169,58,58,135,142,...,-11.00,27.46,27.38,27.71,27.34,28.15,28.40,27.07,27.26,26
Arsenal,26,20,13,12,191,221,69,84,178,206,...,-9.75,29.74,28.98,29.86,29.14,30.57,30.06,29.39,28.87,26
Everton,19,15,10,4,203,131,78,45,153,148,...,-5.50,27.12,27.39,27.40,27.65,28.56,28.20,27.13,27.22,25
Chelsea,22,15,10,5,263,98,93,33,134,174,...,-17.25,31.24,28.49,31.68,28.53,32.48,29.58,30.99,28.30,24
Sheffield United,17,13,9,5,178,143,58,47,156,126,...,-1.25,28.82,29.49,29.27,29.72,30.21,30.25,29.05,29.22,24
Burnley,20,19,5,10,180,185,69,62,169,155,...,4.00,28.55,29.90,28.83,30.20,29.57,30.82,28.47,29.81,23
Crystal Palace,12,13,3,4,175,172,53,65,163,200,...,3.25,28.92,29.72,29.30,29.66,29.78,30.64,28.79,29.46,22
Wolves,21,17,6,10,189,149,56,56,154,157,...,-3.50,28.80,30.06,28.80,30.18,29.59,30.77,28.56,29.71,22
Newcastle,12,12,4,6,172,222,54,64,137,153,...,3.75,27.25,27.29,27.47,27.57,28.58,28.25,27.27,27.12,21
Brighton,17,15,7,6,193,142,56,48,136,133,...,-2.00,26.88,27.91,27.01,28.00,27.89,28.62,26.69,27.65,18
Aston Villa,18,24,8,14,187,212,56,71,154,176,...,5.00,24.89,25.72,25.00,26.07,25.71,26.58,24.74,25.79,17
Bournemouth,17,21,9,10,145,220,50,68,114,174,...,3.25,27.30,27.37,27.54,27.50,28.31,28.21,27.26,27.14,17
Watford,16,17,5,7,200,165,49,65,177,135,...,1.50,27.60,27.20,27.61,27.41,28.31,27.99,27.40,27.03,17
Norwich,19,26,12,9,170,221,66,81,133,159,...,8.25,26.71,27.74,26.94,28.13,28.07,28.85,26.77,27.66,15
West Ham,23,26,13,9,163,154,73,67,134,131,...,3.00,26.39,28.18,26.60,28.45,27.23,29.13,26.37,28.02,15
Southampton,16,31,8,16,186,182,60,79,167,162,...,-1.00,28.29,30.21,28.48,30.54,29.62,31.08,28.26,30.04,14